Feat-8: Add a dimmer
tussharrane/E-Learning-portal pull request #32
Opened 2021-12-07 12:52 UTC by tussharrane

2021-12-07 15:33 UTC, kkyusufk requested changes

2021-12-07 15:33 UTC, kkyusufk commented on src/Components/Screen/Screen.js
> +				)}
Lets make another component for this dimmer

2021-12-07 15:33 UTC, kkyusufk commented on src/Components/Screen/Screen.module.css
> +	z-index: 99;
a really high number, any reason for this?

2021-12-08 04:25 UTC, tussharrane commented on src/Components/Screen/Screen.module.css
> +	z-index: 99;
No particular reason for 99. I will change it to 9.

2021-12-08 09:17 UTC, kkyusufk approved these changes

2021-12-08 09:27 UTC, merged