Feat-9: Add interactive renderers
tussharrane/E-Learning-portal pull request #35
Opened 2021-12-10 07:25 UTC by tussharrane

2021-12-10 09:37 UTC, kkyusufk commented
Okay, here are some thoughts:
- the first 3 vidoes and next 3 mcqs are all part of the same lessons. so I do no expect there to be a drastic change in the UI when switching from video to mcq. I do not see the progress bar, the forward and backward button on mcq screens. 
- I dont expect a seperate screen for showing the correct answer, just a dimmer on screen with a tick mark can be enough.
- I see that when you are developing these new features you do not ask or question anything, you are assuming a lot of things and just doing stuff on your own. Please be more curious and ask more questions in future.

2021-12-10 09:45 UTC, tussharrane commented
@kkyusufk 
Okay ,
So, should I keep this MCQRenderer component and add similar styles as of the video screens. ?
Or, should I render the MCQRenderer instead of the video element inside of the Screen.

2021-12-10 09:55 UTC, kkyusufk commented
> Or, should I render the MCQRenderer instead of the video element inside of the Screen.

with the mcq screens, the lesson now has 6 screens. Depending on that the progress bar should update. So it would fill up after 6 screens. Also try to mix and match, first screen video, next 2 screens mcqs then video. Make one data.json which might be easier.

2021-12-10 11:31 UTC, tussharrane commented
@kkyusufk 
I have added the mcqRenderer  and data.json as we discussed.
I noticed a bug, If we go to the previous screens and re-select the mcq answers, the score increases. 
For this, should I create a global state variable which tracks which mcq question has been marked correct, and so the score wont go more than the number of question.

2021-12-10 11:51 UTC, kkyusufk commented
> For this, should I create a global state variable which tracks which mcq question has been marked correct, and so the score wont go more than the number of question.

Yup, something like that
But lets track it in a seperate piece of work, I would just mark the screen as completed once its finished.

![image](https://user-images.githubusercontent.com/22116082/145570121-d35e262c-1784-469b-967a-7c568e4383c7.png)
this score thing at the top, it should be removed

2021-12-10 14:53 UTC, kkyusufk commented
![image](https://user-images.githubusercontent.com/22116082/145593601-c3eb3065-b995-4194-b8ee-4d460a5d99c3.png)
pause button is disabled in mc renderers

2021-12-10 14:54 UTC, kkyusufk commented
forward button is disabled on last screen but it is still hover-able. It should not be hover-able

2021-12-10 14:55 UTC, kkyusufk commented
Just a heads up,
Whenever you add new features, do a manual play through and make sure new features did not break old working features

2021-12-10 14:59 UTC, kkyusufk requested changes

2021-12-10 14:59 UTC, kkyusufk commented on src/Components/McqRenderer/McqRenderer.js
> +	const [showSubmitBtn, setShowSubmitBtn] = useState(false);
`showSubmitButton`

2021-12-10 14:59 UTC, kkyusufk commented on src/Components/MainContainer/MainContainer.js
> +	const onCurrScreenEnded = () => {
onCurrentScreenEnded

2021-12-10 14:59 UTC, kkyusufk commented on src/store/actionCreators.js
> +const incrementScore = () => ({ type: actions.ADD_SCORE });
out of scope of this change, but you can destructure all these actions above and use them.
ex: `import { ADD_SCORE } from './actions'`

2021-12-10 15:06 UTC, tussharrane commented
> pause button is disabled in mc renderers
@kkyusufk 
In mcq, play/pause button has no function as there is no video to play or pause. 
Should I keep it disabled and if not, what should the pause/play button do?

2021-12-13 08:35 UTC, kkyusufk commented
> > pause button is disabled in mc renderers
> 
> @kkyusufk In mcq, play/pause button has no function as there is no video to play or pause. Should I keep it disabled and if not, what should the pause/play button do?

play-pause should disable the UI, thats what the functionality should be

2021-12-13 08:44 UTC, tussharrane commented
> play-pause should disable the UI, thats what the functionality should be

@kkyusufk 
should the mcq Options be disabled as well when paused? or just the next and previous buttons..

2021-12-13 09:14 UTC, tussharrane commented
@kkyusufk 
When paused the ui buttons are disabled also a Dimmer to show the screen is Paused just like in Video Screens.

2021-12-13 09:34 UTC, kkyusufk approved these changes

2021-12-13 09:42 UTC, merged