Added StoreType in Store.ts and redux-dev-tools to be typescript compatible
tussharrane/E-Learning-portal pull request #50
Opened 2021-12-22 11:45 UTC by tussharrane

2021-12-22 15:29 UTC, kkyusufk requested changes

2021-12-22 15:29 UTC, kkyusufk commented on package.json
> +		"redux-devtools-extension": "^2.13.9",
I do not understand, why doesnt the old way works with TS?

2021-12-23 04:19 UTC, tussharrane commented on package.json
> +		"redux-devtools-extension": "^2.13.9",
> I do not understand, why doesnt the old way works with TS?

@kkyusufk  with the old Code -- ` window.__REDUX_DEVTOOLS_EXTENSION__ &&
		window.__REDUX_DEVTOOLS_EXTENSION__()` TS throws error  -- `REDUX_DEVTOOLS_EXTENSION is not a function on window`.

2021-12-23 09:14 UTC, kkyusufk commented on package.json
> +		"redux-devtools-extension": "^2.13.9",
Cool, thanks!

2021-12-23 09:14 UTC, kkyusufk approved these changes

2021-12-23 09:24 UTC, merged