Added Mcqrenderer.tsx
tussharrane/E-Learning-portal pull request #51
Opened 2021-12-23 10:46 UTC by tussharrane

2022-01-04 09:34 UTC, kkyusufk requested changes

2022-01-04 09:34 UTC, kkyusufk commented on src/Components/McqRenderer/McqRenderer.tsx
> +	data: { num: number; question: string; options: string[]; ans: number };
`Array<string>` is the style we follow so update that
also `ans` should be `answer`, no short forms please.

2022-01-04 09:34 UTC, kkyusufk commented on src/Components/McqRenderer/McqRenderer.tsx
> +		setSelectedOption(+optionId);
`selectedOption` is a number but it is also passed a string

2022-01-04 09:34 UTC, kkyusufk commented on src/Components/McqRenderer/McqRenderer.tsx
> +			<Dimmer isActive={evaluation !== null || isPaused}>
what was the reason for this null check?

2022-01-04 09:56 UTC, tussharrane commented on src/Components/McqRenderer/McqRenderer.tsx
> +			<Dimmer isActive={evaluation !== null || isPaused}>
@kkyusufk 
isActive prop expects a boolean, and so this null check makes sure that isActive is not provided with` string | Boolean` type

2022-01-04 10:00 UTC, tussharrane commented on src/Components/McqRenderer/McqRenderer.tsx
> +		setSelectedOption(+optionId);
@kkyusufk 
if you are referring to the empty string, then that will be converted to `0` before passing into `selectedOption`.
should I assign `-1` instead of '' to  make it more clear?

2022-01-05 07:14 UTC, kkyusufk approved these changes

2022-01-05 07:18 UTC, merged